chore(ci): add release notes to github releases automatically

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -188,6 +188,8 @@ jobs:
             curl -fsSL "https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64" -o "${HOME}/bin/dasel"
             chmod +x "${HOME}/bin/dasel"
 
+            curl -fsSL "https://github.com/orhun/git-cliff/releases/download/v0.7.0/git-cliff-0.7.0-x86_64-unknown-linux-gnu.tar.gz" | tar -C "${HOME}/bin" --strip-components=1 -xz "git-cliff-0.7.0/git-cliff"
+
       - run:
           name: 'Publish binaries to GitHub Releases'
           command: |
@@ -196,7 +198,31 @@ jobs:
 
             export ARTIFACTS_DIR=".out"
             export VERSION=$(dasel select -p toml -s ".package.version" -f packages_rs/nextclade/Cargo.toml)
-            ./scripts/publish_github_releases.sh
+
+            (./scripts/extract-release-notes.py CHANGELOG.md; git cliff --unreleased) | github-release release \
+              --user "${CIRCLE_PROJECT_USERNAME}" \
+              --repo "${CIRCLE_PROJECT_REPONAME}" \
+              --tag "${VERSION}" \
+              --target "${CIRCLE_SHA1}" \
+              --description - \
+              --security-token "${GITHUB_TOKEN}" \
+            || true
+
+            # Look like the release appears not immediately and if upload is following too quickly
+            # it fails because it cannot find the release. So let's wait an arbitrary amount of time here.
+            sleep 7
+
+            for filename in ${ARTIFACTS_DIR}/*; do
+              github-release upload \
+                --file "${filename}" \
+                --name "$(basename ${filename})" \
+                --user "${CIRCLE_PROJECT_USERNAME}" \
+                --repo "${CIRCLE_PROJECT_REPONAME}" \
+                --tag "${VERSION}" \
+                --security-token "${GITHUB_TOKEN}" \
+                --replace
+            done
+
 
 
   Build-And-Release-Web:
@@ -285,87 +311,85 @@ jobs:
                 circleci-agent step halt
             fi
 
-cli_only: &cli_only
+cli_only: &cli_branches_only
   filters:
     branches:
       only:
-        - release-cli
-        - staging-cli
-        - rust
+        # - release-cli
+        # - staging-cli
+         - rust-release
 
 
-major_branches_only: &major_branches_only
+major_branches_only: &only_major_branches
   filters:
     branches:
       only:
-        - master
-        - staging
-        - release
-        # - rust
+        # - master
+        # - staging
+        # - release
+         - rust-release
 
-major_branches_and_cli_release_only: &major_branches_and_cli_only
+major_branches_and_cli_release_only: &only_major_branches_and_cli_branches
   filters:
     branches:
       only:
-        - master
-        - staging
-        - release
-        - release-cli
-        - staging-cli
-        # - rust
+        # - master
+        # - staging
+        # - release
+        # - release-cli
+        # - staging-cli
+         - rust-release
 
 workflows:
   version: 2
   build:
     jobs:
-#      - Update-Builder-Container:
-#          <<: *major_branches_and_cli_only
-#
-#          context:
-#            - nextclade_macos
-#
-#
-#      - Build-Cli:
-#          <<: *major_branches_and_cli_only
-#
-#          requires:
-#            - Update-Builder-Container
-#
-#          context:
-#            - nextclade_macos
-#
-#          matrix:
-#            parameters:
-#              target_arch:
-#                - x86_64-apple-darwin
-#                - aarch64-apple-darwin
-#                - x86_64-unknown-linux-gnu
-#                - x86_64-pc-windows-gnu
-#                - aarch64-unknown-linux-gnu
-#                - x86_64-unknown-linux-musl
+      - Update-Builder-Container:
+          <<: *only_major_branches_and_cli_branches
+
+          context:
+            - nextclade_macos
+
+
+      - Build-Cli:
+          <<: *cli_branches_only
+
+          requires:
+            - Update-Builder-Container
+
+          context:
+            - nextclade_macos
+
+          matrix:
+            parameters:
+              target_arch:
+                - x86_64-apple-darwin
+                - aarch64-apple-darwin
+                - x86_64-unknown-linux-gnu
+                - x86_64-pc-windows-gnu
+                - aarch64-unknown-linux-gnu
+                - x86_64-unknown-linux-musl
 
 
       - Release-Cli:
-          filters:
-            branches:
-              only:
-                - rust-release
+          <<: *cli_branches_only
 
           context:
             - nextclade_github
 
-#          requires:
-#            - Build-Cli-x86_64-apple-darwin
-#            - Build-Cli-aarch64-apple-darwin
-#            - Build-Cli-x86_64-unknown-linux-gnu
-#            - Build-Cli-x86_64-pc-windows-gnu
-#            - Build-Cli-aarch64-unknown-linux-gnu
-#            - Build-Cli-x86_64-unknown-linux-musl
+          requires:
+            - Build-Cli-x86_64-apple-darwin
+            - Build-Cli-aarch64-apple-darwin
+            - Build-Cli-x86_64-unknown-linux-gnu
+            - Build-Cli-x86_64-pc-windows-gnu
+            - Build-Cli-aarch64-unknown-linux-gnu
+            - Build-Cli-x86_64-unknown-linux-musl
 
-#      - Build-And-Release-Web:
-#          <<: *major_branches_only
-#
-#          # context: nextclade_web_<< pipeline.git.branch >>
-#
-#          requires:
-#            - Update-Builder-Container
+
+      - Build-And-Release-Web:
+          <<: *only_major_branches
+
+          # context: nextclade_web_<< pipeline.git.branch >>
+
+          requires:
+            - Update-Builder-Container
